### ISSUE TITLE
ty

### ISSUE THREAD

**Issue by rezad1393** [williambailey/pacproxy#1]
thanks for this simple proxy
specially for providing the ARM exe that is static(maybe?) and runs on openwrt.
how do I static compile it for ARM my self?

**Comment by williambailey** [comment]
Ok. Not exactly the quickest reply. All the released binaries are static in that you should be able to download and run without any additional dependencies so simply downloading a linux arm release will hopefully be all you need to do.

As for compiling. Its a bit messy as it currently stand in master. If you look at the `v2.0.0-wip` branch then things become a bit easier. Just install the latest version of go and, for arm builds, run `GOOS=linux GOARCH=arm go build -o ./build/pacproxy` or `GOOS=linux GOARCH=arm64 go build -o ./build/pacproxy`

**Comment by rezad1393** [comment]
`$ GOOS=linux GOARCH=arm go build -o ./build/pacproxy
pacproxy.go:11:2: cannot find package "github.com/williambailey/pacproxy/pac" in any of:
        /usr/local/go/src/github.com/williambailey/pacproxy/pac (from $GOROOT)
        ($GOPATH not set)
`
how do I fix this?
