### ISSUE TITLE
Error loop on 2.0.0 beta 1 on macOS 10.13.2.

### ISSUE THREAD

**Issue by kathampy** [williambailey/pacproxy#4]
2.0.0 beta 1 shows this error and goes into an infinite loop on macOS 10.13.2.

> pacproxy -c "http://proxy/proxy.pac" -l "127.0.0.1:3128" -v
> 2017/12/19 06:57:18.742919 otto.go:57: started OttoEngine
> 2017/12/19 06:57:18.742950 pacproxy.go:76: Listening on "127.0.0.1:3128"
> 2017/12/19 06:57:18.743028 otto.go:288: stopping OttoEngine
> 2017/12/19 06:57:18.743036 otto.go:272: stopped OttoEngine
> 2017/12/19 06:57:18.743042 pacproxy.go:53: Recovered
> 2017/12/19 06:57:18.743049 otto.go:73: initialising OttoEngine
> 2017/12/19 06:57:18.743304 loader.go:46: loading pac from URL "http://proxy/proxy.pac"
> 2017/12/19 06:57:18.748731 otto.go:254: PAC:
> function FindProxyForURL(url, host) {

**Comment by williambailey** [comment]
Thanks for the bug report. I'll try to find some time this weekend to push a new beta that will hopefully give further information as to what it's trying to recover from. In the meantime can you try to run 2.0.0 beta 1 with the following arguments and let me know if that still causes an infinite loop.

```bash
pacproxy -c "DIRECT" -l "127.0.0.1:3128" -v
```
Can you just confirm if its `macOS 10.3.2` (in the title) or `macOS 10.13.2` (in the summary).

**Comment by williambailey** [comment]
Just released [2.0.0](/williambailey/pacproxy/releases/tag/v2.0.0). Please give that a go and let me know if you still have issues.

**Comment by kathampy** [comment]
It works fine now, thanks.
