### ISSUE TITLE
Unable to execute pacproxy_2.0.0_windows_amd64.exe

### ISSUE THREAD

**Issue by michalsvec** [williambailey/pacproxy#8]
I just downloaded pacproxy_2.0.0_windows_amd64.exe and when executing it returns 

```
$ ./pacproxy_2.0.0_windows_amd64.exe
panic: open : The system cannot find the file specified.

goroutine 1 [running]:
log.Panic(0xc04206ff20, 0x1, 0x1)
        /usr/local/Cellar/go/1.9.2/libexec/src/log/log.go:326 +0xc7
main.main()
        /Users/williambailey/Development/go/src/github.com/williambailey/pacproxy/pacproxy.go:47 +0x1e7
```

Are you sure it's correctly built?

Thank you.

**Comment by ohk2kt3t4** [comment]
Working fine here. You have to give it some input or it panics, for example

```
pacproxy.exe -c http://myintranet.com/proxy.pac
```

**Comment by michalsvec** [comment]
Then it would be great to have a user friendly error message.

**Comment by ammgws** [comment]
I've opened a PR just for that, if you can build it then try it out.

**Comment by williambailey** [comment]
I've finally got around to releasing v2.0.2 which address this issue.
